name: CI
on: [push, pull_request]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get install -y cmark tcl tcllib libsqlite3-tcl
    - name: Test
      run: |
        make test

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download dependencies
      run: |
        Invoke-WebRequest http://kitcreator.rkeene.org/kits/ae78c6ebb1cca64104a326db1be0110e8b2457c9/tclkit.exe -OutFile tclkit.exe

        Set-Location ..
        git clone https://github.com/tclssg/packer
        Set-Location tclssg
    - name: Build
      run: |
        .\tclkit.exe windows-ci.tcl
    - name: Test
      run: |
        .\tclkit.exe tests.tcl
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          artifacts/
