name: CI
on: [push, pull_request]
jobs:
  bsd:
    runs-on: ${{ matrix.os.host }}
    strategy:
      matrix:
        os:
          - name: freebsd
            architecture: x86-64
            version: '14.0'
            host: ubuntu-latest
          - name: netbsd
            architecture: x86-64
            version: '10.0'
            host: ubuntu-latest
          - name: openbsd
            architecture: x86-64
            version: '7.4'
            host: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run CI script on ${{ matrix.os.name }}
        uses: cross-platform-actions/action@v0.24.0
        with:
          operating_system: ${{ matrix.os.name }}
          architecture: ${{ matrix.os.architecture }}
          version: ${{ matrix.os.version }}
          shell: bash
          run: |
            ci/install-deps.sh
            make test
  linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        ci/install-deps.sh
    - name: Test
      run: |
        make test

  macos:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        brew install cmark tcl-tk
    - name: Test
      run: |
        make test

  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Download dependencies
      run: |
        Invoke-WebRequest http://kitcreator.rkeene.org/kits/ae78c6ebb1cca64104a326db1be0110e8b2457c9/tclkit.exe -OutFile tclkit.exe

        Set-Location ..
        git clone https://github.com/tclssg/packer
        Set-Location tclssg
    - name: Build
      run: |
        .\tclkit.exe ci\windows.tcl
    - name: Test
      run: |
        .\tclkit.exe tests.tcl
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: |
          artifacts/
